package com.lutem.mvp.model;

/**
 * Indicates the source of game attribute tagging.
 * Used to track how game metadata (emotional goals, energy level, etc.) was determined.
 */
public enum TaggingSource {
    /**
     * Manually curated by Lutem team - highest confidence
     */
    MANUAL,
    
    /**
     * Generated by AI based on RAWG/external data
     */
    AI_GENERATED,
    
    /**
     * User has reviewed and adjusted AI-generated tags
     */
    USER_ADJUSTED,
    
    /**
     * Game imported but not yet tagged - excluded from smart recommendations
     */
    PENDING
}
